
resolver: nightly-2023-05-10

packages:
  - beam-sqlite
  - beam-postgres
  - beam-core
  - beam-migrate
  # - beam-migrate-cli

nix:
  shell-file: shell.nix

extra-deps:
- vector-sized-1.5.0
# - hint-0.9.0.6
