
resolver: nightly-2024-06-12

nix:
  packages:
  - postgresql
  path:
  - "nixpkgs=/home/tom/tools/nixpkgs"

packages:
- beam-sqlite
- beam-postgres
- beam-core
- beam-migrate

# nix:
#   shell-file: shell.nix
